name: Run Tests and Generate Code Coverage

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'

      - name: Install dependencies
        run: |
          dotnet restore

      - name: Run tests and collect coverage
        run: |
          dotnet test --collect:"XPlat Code Coverage"  

      - name: Find coverage file
        id: find-coverage
        run: |
          COVERAGE_FILE=$(find ./IronSoftware.OldPhonePad.Tests/TestResults/ -name "coverage.cobertura.xml" -print -quit)
          echo "coverage_file=$COVERAGE_FILE" >> $GITHUB_ENV

      - name: Install ReportGenerator
        run: |
          dotnet tool install --global dotnet-reportgenerator-globaltool
          export PATH="$PATH:/root/.dotnet/tools"

      - name: Generate code coverage report
        run: |
          reportgenerator "-reports:${{ env.coverage_file }}" "-targetdir:./CodeCoverageReport" -reporttypes:TextSummary
          cat ./CodeCoverageReport/summary.txt
